language: bash

matrix:
  include:
    - os: linux
      sudo: required
    - os: osx
      osx_image: xcode9.3beta


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y coreutils openssl vim-common; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://ftp-master.debian.org/keys/archive-key-7.0.asc | sudo apt-key add -; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user bashate; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install coreutils || brew outdated coreutils || brew upgrade coreutils; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install findutils || brew outdated findutils || brew upgrade findutils; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/findutils/libexec/gnubin:$PATH"; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-sed || brew outdated gnu-sed || brew upgrade gnu-sed; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl || brew outdated openssl || brew upgrade openssl; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'shopt -s globstar; shellcheck -e 2012 **/*.sh'; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'shopt -s globstar; bashate -i E006,E011 **/*.sh'; fi
 - ./lockbox.sh -v
 - ./lockbox.sh -h
 - ./unit-test.sh
