language: bash

matrix:
  include:
    - os: linux
      dist: precise
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode6.4
    - os: osx
    - os: osx
      osx_image: xcode9.3beta


before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y openssl vim-common coreutils; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://ftp-master.debian.org/keys/archive-key-7.0.asc | sudo apt-key add -; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y shellcheck; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip install --user bashate; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew outdated coreutils || brew upgrade coreutils; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ln -s /usr/local/bin/gmd5sum /usr/local/bin/md5sum; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ln -s /usr/local/bin/gsha512sum /usr/local/bin/sha512sum; fi

script:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'shopt -s globstar; shellcheck -e 2012 **/*.sh'; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash -c 'shopt -s globstar; bashate -i E006,E011 **/*.sh'; fi
 - ./lockbox.sh -v
 - ./lockbox.sh -h
 - ./unit-test.sh
